// Dashboard mock data — 数据库不可用时的完整降级数据
export const MOCK_DASHBOARD = {
  aiNewsTotal: 25,
  ghProjectsTotal: 25,
  avgPositivePct: 69,
  activeDiscussions: 847,
  categoryDistribution: [
    { category: "llm", label: "大模型", count: 4, color: "from-blue-500 to-cyan-400" },
    { category: "agents", label: "AI Agent", count: 5, color: "from-violet-500 to-purple-400" },
    { category: "tools", label: "开发工具", count: 5, color: "from-amber-500 to-orange-400" },
    { category: "research", label: "学术研究", count: 5, color: "from-emerald-500 to-teal-400" },
    { category: "open-source", label: "开源", count: 4, color: "from-rose-500 to-pink-400" },
    { category: "multimodal", label: "多模态", count: 2, color: "from-indigo-500 to-blue-400" },
  ],
  weeklySentiment: [
    { day: "周一", positive: 65, negative: 15, neutral: 20 },
    { day: "周二", positive: 72, negative: 12, neutral: 16 },
    { day: "周三", positive: 58, negative: 22, neutral: 20 },
    { day: "周四", positive: 75, negative: 10, neutral: 15 },
    { day: "周五", positive: 68, negative: 18, neutral: 14 },
    { day: "周六", positive: 62, negative: 20, neutral: 18 },
    { day: "周日", positive: 71, negative: 13, neutral: 16 },
  ],
  hotKeywords: [
    { word: "Agent", weight: 95, category: "agents" },
    { word: "GPT-5", weight: 88, category: "llm" },
    { word: "多模态", weight: 82, category: "multimodal" },
    { word: "开源", weight: 78, category: "open-source" },
    { word: "MCP", weight: 75, category: "tools" },
    { word: "Claude", weight: 72, category: "llm" },
    { word: "推理", weight: 68, category: "research" },
    { word: "MoE", weight: 65, category: "research" },
    { word: "Llama 4", weight: 62, category: "open-source" },
    { word: "DeepSeek", weight: 60, category: "llm" },
    { word: "RAG", weight: 55, category: "research" },
    { word: "NVIDIA", weight: 52, category: "tools" },
    { word: "安全", weight: 48, category: "research" },
    { word: "Copilot", weight: 45, category: "tools" },
    { word: "Gemini", weight: 42, category: "multimodal" },
    { word: "R2", weight: 40, category: "llm" },
    { word: "LangChain", weight: 38, category: "agents" },
    { word: "Mistral", weight: 35, category: "open-source" },
    { word: "Agent Studio", weight: 32, category: "agents" },
    { word: "B300", weight: 30, category: "tools" },
  ],
};
